export const jobs = [
  {
    title: 'frontend developer',
    tags: ['full-time', 'new'],
    description: 'Looking for a skilled frontend developer to join our team. Experience with React and responsive design is a plus.',
    price: 25,
  },
  {
    title: 'data scientist',
    tags: ['full-time', 'remote'],
    description: 'Exciting opportunity for a data scientist to work on cutting-edge projects. Strong background in machine learning and data analysis required.',
    price: 3,
  },
  {
    title: 'UX/UI designer',
    tags: ['part-time', 'new'],
    description: 'We\'re seeking a creative UX/UI designer to enhance user experiences. Proficiency in design tools such as Sketch or Figma is a must.',
    price: 2,
  },
  {
    title: 'backend developer',
    tags: ['full-time'],
    description: 'Join our backend development team to build robust and scalable server-side applications. Experience with Node.js and databases is essential.',
    price: 28,
  },
  {
    title: 'product manager',
    tags: ['full-time', 'urgent'],
    description: 'We\'re urgently hiring a skilled product manager to lead product development. Strong communication and project management skills are required.',
    price: 35,
  },
  {
    title: 'systems administrator',
    tags: ['contract', 'new'],
    description: 'Seeking a systems administrator for a short-term contract. Experience with system maintenance and troubleshooting is a must.',
    price: 22,
  },
  {
    title: 'mobile app developer',
    tags: ['full-time'],
    description: 'Join our mobile app development team to create innovative and user-friendly applications. Proficiency in Swift or Kotlin is required.',
    price: 26,
  },
  {
    title: 'QA engineer',
    tags: ['full-time', 'remote'],
    description: 'We\'re hiring a QA engineer to ensure the quality of our software products. Experience with automated testing tools is preferred.',
    price: 24,
  },
  {
    title: 'technical writer',
    tags: ['part-time', 'new'],
    description: 'Exciting part-time opportunity for a technical writer. Create clear and concise documentation for our software products.',
    price: 18,
  },
  {
    title: 'DevOps engineer',
    tags: ['full-time', 'urgent'],
    description: 'Urgently seeking a DevOps engineer to streamline our development and deployment processes. Experience with CI/CD is required.',
    price: 32,
  },
]

export const profiles = [
  {
    title: 'Alice Developer',
    tags: ['full-time', 'new'],
    description: 'Experienced frontend developer specializing in React and responsive design.',
    price: 0.25,
    star: 4.5,
    ratingCount: 30,
  },
  {
    title: 'Bob Data Scientist',
    tags: ['full-time', 'remote'],
    description: 'Skilled data scientist with expertise in machine learning and data analysis.',
    price: 0.3,
    star: 4.2,
    ratingCount: 25,
  },
  {
    title: 'Charlie Designer',
    tags: ['part-time', 'new'],
    description: 'Creative UX/UI designer proficient in Sketch and Figma.',
    price: 0.2,
    star: 4.0,
    ratingCount: 20,
  },
  {
    title: 'David Backend Developer',
    tags: ['full-time'],
    description: 'Experienced backend developer with expertise in Node.js and databases.',
    price: 0.28,
    star: 4.7,
    ratingCount: 35,
  },
  {
    title: 'Eva Product Manager',
    tags: ['full-time', 'urgent'],
    description: 'Skilled product manager with strong communication and project management skills.',
    price: 0.35,
    star: 4.3,
    ratingCount: 40,
  },
  {
    title: 'Frank Systems Administrator',
    tags: ['contract', 'new'],
    description: 'Systems administrator for short-term contract with experience in maintenance and troubleshooting.',
    price: 0.22,
    star: 4.1,
    ratingCount: 15,
  },
  {
    title: 'Grace Mobile App Developer',
    tags: ['full-time'],
    description: 'Join our mobile app development team to create innovative and user-friendly applications.',
    price: 0.26,
    star: 4.6,
    ratingCount: 28,
  },
  {
    title: 'Henry QA Engineer',
    tags: ['full-time', 'remote'],
    description: 'QA engineer ensuring the quality of our software products with experience in automated testing tools.',
    price: 0.24,
    star: 4.4,
    ratingCount: 22,
  },
]
